#!/usr/bin/env python
import sys

Import("env")

env.add_source_files(env.scene_sources, "*.cpp")
if sys.platform == "darwin":
    env.add_source_files(env.scene_sources, "*.m")


SConscript("default_theme/SCsub")
