#!/usr/bin/env python

Import("env")



thirdparty_obj = []

thirdparty_sources = "#thirdparty/misc/mikktspace.c"

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.scene_sources += thirdparty_obj

# Godot source files

scene_obj = []

env.add_source_files(scene_obj, "*.cpp")
if env["platform"] in ["iphone", "osx", "server"]:
    env.add_source_files(scene_obj, "*.m")
env.scene_sources += scene_obj

# Needed to force rebuilding the scene files when the thirdparty code is updated.
env.Depends(scene_obj, thirdparty_obj)

SConscript("default_theme/SCsub")
