#!/usr/bin/env python

Import('env')

env.add_source_files(env.scene_sources, "*.cpp")
if env["platform"] == "iphone" or env["platform"] == "osx":
    env.add_source_files(env.scene_sources, "*.m")


SConscript("default_theme/SCsub")
