name: 🤖 Android Builds
on: [public]

# Global Settings
env:
  SCONSFLAGS: platform=android verbose=yes debug_symbols=yes --jobs=2 tools=no module_firebase_enabled=no module_bullet_enabled=no module_websocket_enabled=no game_center=no disable_3d=yes
  SCONS_CACHE_LIMIT: 4096
  ANDROID_NDK_VERSION: 21.1.6352462

jobs:
  android-template:
    runs-on: "ubuntu-20.04"

    name: Template (target=release_debug,debug; tools=no)

    steps:
      - name: Checkout Engine
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Install Android NDK r21
        run: |
          sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;${{env.ANDROID_NDK_VERSION}}'

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        uses: actions/cache@v2
        with:
          path: .scons_cache
          key: ${{matrix.token}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{matrix.token}}-${{github.ref}}-${{github.sha}}
            ${{matrix.token}}-${{github.ref}}
            ${{matrix.token}}

      # Use python 3.x release (works cross platform)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/${{env.ANDROID_NDK_VERSION}}/
        run: |
          scons target=release_debug tools=no android_arch=armv7
          scons target=debug tools=no android_arch=armv7
          scons target=release_debug tools=no android_arch=arm64v8
          scons target=debug tools=no android_arch=arm64v8
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin/*
          retention-days: 14